package se.nackademin.violofsson.spring.cruddypeople.domain;

public enum Arcana {
    FOOL, MAGICIAN, HIGH_PRIESTESS, EMPRESS, EMPEROR, HIEROPHANT, LOVERS,
    CHARIOT, JUSTICE, HERMIT, WHEEL_OF_FORTUNE, STRENGTH, HANGED_MAN, DEATH,
    TEMPERANCE, DEVIL, TOWER, STAR, MOON, SUN, JUDGEMENT, WORLD
}
